name: BuildCI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'backend/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true  

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Perms Gradle
        run: chmod 777 gradlew
#      - name: Set Key
#        run: echo "${{ secrets.LEGACYSENDKEYAPPB }}" | base64 -d > app/LegacySend.keystore
      - name: Build App
#        env:
#          LEGACYSENDKEYCONTREAPP: ${{ secrets.LEGACYSENDKEYCONTREAPP }}
        run: ./gradlew :app:assembleDebug --no-daemon
#      - name: Enable KVM group perms
#        run: |
#          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#          sudo udevadm control --reload-rules
#          sudo udevadm trigger --name-match=kvm
#      - name: Test App
#        uses: ReactiveCircus/android-emulator-runner@v2.38.0
#        with:
#          api-level: 16
#          target: default
#          arch: x86
#          profile: Nexus 4
#          script: |
#            adb wait-for-device
#            adb install "app/build/outputs/apk/debug/app-debug.apk"
#            chmod +x ./tests/test-app.sh
#            ./tests/test-app.sh

      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: LegacySendApp
          path: app/build/outputs/apk/debug/*.apk
